import React from "react";
import { ArrowLeft } from "lucide-react";

interface TermsOfUseProps {
  onBack: () => void;
}

export default function TermsOfUse({ onBack }: TermsOfUseProps) {
  return (
    <div className="space-y-6 max-w-2xl">
      <div className="flex items-center gap-2">
        <button
          onClick={onBack}
          className="p-1.5 text-slate-400 hover:text-white bg-slate-900 border border-slate-800 hover:border-slate-700 rounded-xl transition-all"
          title="Back"
        >
          <ArrowLeft size={14} />
        </button>
        <h2 className="text-lg font-semibold text-slate-100">Terms of Use</h2>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-5 text-sm text-slate-300 leading-relaxed">
        <p className="text-xs text-slate-500">Last updated: July 8, 2026</p>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Acceptance of Terms</h3>
          <p>
            This service is operated by Ergas Basher Tech Group ("we", "us", "our"). By connecting
            your WhatsApp number or using this dashboard, you agree to these terms.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Description of Service</h3>
          <p>
            This service lets you save notes, tasks, and reminders via WhatsApp or this web
            dashboard, and uses AI to categorize content, schedule reminders, and answer questions
            about what you've saved.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Your Responsibilities</h3>
          <p>
            One account per phone number. Don't use this service to store or transmit illegal
            content, or to impersonate someone else's phone number.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">AI-Generated Content Disclaimer</h3>
          <p>
            Categorization, summaries, and reminder times are generated by AI and may occasionally
            be wrong — including getting a reminder's time or timezone incorrect. Please verify
            anything time-sensitive or important rather than relying on it exclusively.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Account Termination</h3>
          <p>
            You can delete your account and all associated data at any time from Settings. We may
            suspend or terminate accounts that abuse the service.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Limitation of Liability</h3>
          <p>
            This service is provided "as is" without warranties of any kind. We are not liable for
            missed reminders, data loss, or any damages arising from use of this service, to the
            fullest extent permitted by law.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Governing Law</h3>
          <p>
            This service is offered to users globally, without restriction to a specific country
            or region. Where local law grants you rights that cannot be waived, those rights are
            unaffected by these terms.
          </p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Changes to These Terms</h3>
          <p>We may update these terms from time to time. Material changes will be reflected by updating the date above.</p>
        </section>

        <section className="space-y-2">
          <h3 className="text-slate-100 font-semibold">Contact</h3>
          <p>Questions about these terms? Reach us at <span className="font-mono">eluwamonday2017@gmail.com</span>.</p>
        </section>
      </div>
    </div>
  );
}
